name: Build and Push Docker Image

on:
  push:
  
    branches:
      - main
  
  

env:
  ACR_NAME: byefrost
  ACR_REGISTRY: ${ACR_NAME}.azurecr.io
  IMAGE_NAME: test-nginx
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to ACR
        
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
        working-directory: ./images

      - name: Build Docker image
        run: docker build -t ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        working-directory: ./images

      - name: Push Docker image to ACR
        run: docker push ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        working-directory: ./images
